### ISSUE TITLE
Uncaught TypeError: el.className.split is not a function

### ISSUE THREAD

**Issue by 100milliongold** [nhn/tui.grid#1164] opened 2020-09-10 04:24 UTC
**Describe the bug**
Error when using SVG Component in Custom Render

**To Reproduce**
1. ServerInformationLayout.js

```
import React , { useRef, useCallback, useEffect , useMemo, } from "react";
import Grid from "@toast-ui/react-grid";
import ServerStatusCompoenets from "./ServerStatusCompoenets";

const ServerInformationLayout = props => {
   const columns2 = useMemo(
    () => [
      { header: "Server Host", name: "server_host", sortable: true },
      {
        header: "Status",
        name: "server_status",
        renderer: {
          type: ServerStatusCompoenets,
          options:{
          }
        },
      },
      { header: "Type", name: "kubernetes_cluster_type", sortable: true },
      { header: "Server IP", name: "server_ip", sortable: true },
      { header: "Authority", name: "authority", sortable: true },
    ],
    []
  );
  return (
      <Grid
              columnOptions={{
                resizable: true,
              }}
              ref={gridRef}
              data={data2}
              header={{
                height: "52px",
              }}
              treeColumnOptions={{ name: "server_host" }}
              columns={columns2}
              minRows={13}
              minRowHeight={50}
              bodyHeight={700}
              Pagination={true}
              showDummyRows={true}
              rowHeight={"auto"}
              pageOptions={{
                useClient: true,
                perPage: 14,
              }}
              scrollX={false}
              scrollY={false}
              // heightResizable={true}
            />
 )
}
export default ServerInformationLayout;
```

2.ServerStatusCompoenets
```
import React from "react";
import ReactDOM from "react-dom";

import { ReactComponent as COMPLETE } from "../../Global/images/status/complete.svg";
import { ReactComponent as REQUEST } from "../../Global/images/status/request.svg";
import { ReactComponent as FAIL } from "../../Global/images/status/fail.svg";

export default class ServerStatusComponents {
  constructor(props) {
    const rootDom = document.createElement("div");
    rootDom.style.textAlign = "center";
    rootDom.className = "actions";
    rootDom.style.overflow = "hidden";
    this.el = rootDom;
    // set instance property for grid
    this.props = props;
    if (props.columnInfo.renderer.options) {
    }
    this.render(props);
  }

  getElement() {
    return this.el;
  }


  render(props) {
    const status = props.value;
    const element = (
      <div className="test">
        {status === "wait" && <REQUEST />}
        {status === "success" && <COMPLETE />}
        {status === "fail" && <FAIL />}
      </div>
    );
    ReactDOM.render(element, this.el);
  }
}
```

**Expected behavior**
[https://nhn.github.io/tui.grid/latest/tutorial-example04-custom-renderer 
](https://nhn.github.io/tui.grid/latest/tutorial-example04-custom-renderer 
)
**Screenshots**
Error when clicking on the corresponding component 

```
Uncaught TypeError: el.className.split is not a function
    at Object.hasClass (inArray.js:5)
    at Object.BodyAreaComp._this.handleMouseDown [as mousedown] (bootstrap:86)
    at HTMLDivElement.eventProxy (customEvents.js:33)
hasClass @ inArray.js:5
BodyAreaComp._this.handleMouseDown @ bootstrap:86
eventProxy @ customEvents.js:33
```

**Desktop (please complete the following information):**
 - Device : MacBook Pro (16-inch, 2019)
 - OS: MAC OS 10.15.6(19G2021)
 - Browser: chrome
 - Version: "@toast-ui/react-grid": "^4.15.0"

**Additional context**

**Comment by js87zz** [comment] 2020-09-16 04:52
@100milliongold 
Sorry for late replying.
Can you give your code in code sandbox for resolving and debugging your issue? Because It is difficult for us to reproduce every issue.

**Comment by 100milliongold** [comment] 2020-09-16 05:28
> @100milliongold
> Sorry for late replying.
> Can you give your code in code sandbox for resolving and debugging your issue? Because It is difficult for us to reproduce every issue.

This is the implemented page you requested.

[https://codesandbox.io/s/fancy-https-1i2gq?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/fancy-https-1i2gq?fontsize=14&hidenavigation=1&theme=dark)

**Comment by js87zz** [comment] 2020-09-17 06:09
@100milliongold 
I checked your issue. It will be fixed. Thank you!

**Closed** 2020-09-18 04:22 UTC
Labels: Bug
